DROP DATABASE insetos_db;

CREATE DATABASE IF NOT EXISTS insetos_db;
USE insetos_db;

CREATE TABLE insetos (
    id_insetos INT AUTO_INCREMENT PRIMARY KEY,
    nome_insetos VARCHAR(50) NOT NULL,
    nc_insetos VARCHAR(50) NOT NULL,
    ordem_insetos VARCHAR(65) NOT NULL,
    familia_insetos VARCHAR(65) NOT NULL,
    dieta_insetos VARCHAR(50) NOT NULL,
    destaque BOOLEAN NOT NULL DEFAULT 0,
    curisidade TEXT,
    foto_insetos TEXT
);

INSERT INTO insetos(nome_insetos, nc_insetos, ordem_insetos, familia_insetos, dieta_insetos, curisidade) VALUES
('Besouro Rinoceronte', 'Oryctes nasicornis', 'insetos', 'Scarabaeidae', 'Detritívoro', 'Consegue levantar até vezes o seu próprio peso, equivalente a um humano erguer vários carros.'),
('Besouro Hércules', 'Dynastes hercules', 'insetos', 'Scarabaeidae', 'Detritívoro', 'É considerado um dos maiores insetoss do mundo e possui um chifre enorme usado para disputas territoriais.'),
('Besouro Rola Bosta', 'Scarabaeus sacer', 'insetos', 'Scarabaeidae', 'Coprófago', 'Navega guiando se pela luz da Via Láctea para rolar suas bolas de esterco em linha reta.'),
('Besouro Golias', 'Goliathus goliatus', 'insetos', 'Scarabaeidae', 'Detritívoro', 'Pode pesar mais de gramas na fase larval, sendo um dos insetoss mais pesados da Terra.'),
('Besouro Elefante', 'Megasoma elephas', 'insetos', 'Scarabaeidae', 'Detritívoro', 'Seu nome vem de seu grande porte e do chifre curvado que lembra a tromba de um elefante.'),
('Besouro Marmorado', 'Anomala dubia', 'insetos', 'Scarabaeidae', 'Herbívoro', 'Suas larvas vivem enterradas no solo se alimentando de raízes em decomposição por meses.'),
('Besouro Verde das Flores', 'Cetonia aurata', 'insetos', 'Scarabaeidae', 'Nectarívoro', 'Possui uma coloração metálica brilhante que confere camuflagem natural entre folhagens e pétalas.'),
('Besouro Atlas', 'Chalcosoma atlas', 'insetos', 'Scarabaeidae', 'Detritívoro', 'Os machos usam seus chifres tridivididos para arremessar rivais para longe durante brigas por fêmeas.'),
('Besouro Ouro', 'Chrysina resplendens', 'insetos', 'Scarabaeidae', 'Herbívoro', 'Sua carcaça brilha como ouro puro devido a estruturas microscópicas que refletem a luz.'),
('Besouro das Videiras', 'Pelidnota punctata', 'insetos', 'Scarabaeidae', 'Herbívoro', 'Atrai se facilmente por luzes artificiais durante as noites quentes de verão.'),
('Besouro Violino', 'Mormolyce phyllodes', 'insetos', 'Carabidae', 'Carnívoro', 'Possui um corpo extremamente achatado e alongado, adaptado para viver sob cascas finas de árvores.'),
('Besouro Bombardeiro', 'Brachinus crepitans', 'insetos', 'Carabidae', 'Carnívoro', 'Dispara um jato químico fervendo a °C misturando compostos explosivos em seu abdômen.'),
('Besouro Caçador Dourado', 'Calosoma sycophanta', 'insetos', 'Carabidae', 'Carnívoro', 'É um excelente predador de lagartas desfolhadoras, ajudando a controlar pragas florestais.'),
('Besouro Tigre Verde', 'Cicindela campestris', 'insetos', 'Carabidae', 'Carnívoro', 'Corre tão rápido que precisa parar de enxergar temporariamente para processar as imagens visuais.'),
('Besouro Carabídeo Violeta', 'Carabus violaceus', 'insetos', 'Carabidae', 'Carnívoro', 'Exala um odor defensivo forte e desagradável quando ameaçado por predadores.'),
('Besouro Corredor Noturno', 'Nebria brevicollis', 'insetos', 'Carabidae', 'Carnívoro', 'Ativo durante a noite, caça ativamente aranhas e outros insetoss no solo da floresta.'),
('Besouro Tigre Praiano', 'Cicindela hybrida', 'insetos', 'Carabidae', 'Carnívoro', 'Habita dunas de areia costeiras, onde caça pequenas presas com mandíbulas afiadas.'),
('Besouro Caçador Catarina', 'Calosoma inquisitor', 'insetos', 'Carabidae', 'Carnívoro', 'Capaz de subir em copas de árvores para caçar lagartas vorazes que atacam carvalhos.'),
('Besouro Grão Negro', 'Harpalus rufipes', 'insetos', 'Carabidae', 'Onívoro', 'Embora seja carnívoro, ocasionalmente consome sementes e grãos caídos no solo.'),
('Besouro Bombardeiro Gigante', 'Pheropsophus verticalis', 'insetos', 'Carabidae', 'Carnívoro', 'Possui uma câmara de reação interna mais desenvolvida, permitindo múltiplos disparos químicos consecutivos.'),
('Besouro Sombrio de Cape', 'Circellium bacchus', 'insetos', 'Scarabaeidae', 'Coprófago', 'Um dos poucos Besouros dung que adaptaram se perfeitamente a climas áridos sem voar.'),
('Besouro do Deserto de Namibe', 'Pachysoma striatum', 'insetos', 'Scarabaeidae', 'Detritívoro', 'Recolhe umidade da neblina matinal usando ranhuras especiais em suas costas.'),
('Besouro Cadeia de Avis', 'Pachysoma denticolle', 'insetos', 'Scarabaeidae', 'Detritívoro', 'Caminha por areias quentes do deserto em busca de detritos orgânicos levados pelo vento.'),
('Besouro Rola Bosta Caminhador', 'Scarabaeus ambiguus', 'insetos', 'Scarabaeidae', 'Coprófago', 'Em vez de rolar, empurra esterco usando as pernas traseiras adaptadas como pás.'),
('Besouro do Deserto Coletor', 'Pachysoma hippocrates', 'insetos', 'Scarabaeidae', 'Detritívoro', 'Suas patas curtas e robustas evitam que afunde na areia fofa durante o forrageamento.'),
('Escaravelho Sombrio de Richtersveld', 'Circellium morbillosum', 'insetos', 'Scarabaeidae', 'Coprófago', 'Sobrevive a variações térmicas extremas em montanhas áridas da África do Sul.'),
('Besouro Rola Bosta Gordo', 'Eucranium arachnoides', 'insetos', 'Scarabaeidae', 'Coprófago', 'Possui um abdômen abaulado que armazena reservas de gordura para períodos de escassez.'),
('Besouro Corredor das Pampas', 'Glyphoderus sterquilinus', 'insetos', 'Scarabaeidae', 'Coprófago', 'Adapta se a campos abertos gramados, correndo rapidamente entre touceiras de capim.'),
('Besouro Escavador Siderus', 'Glyphoderus monticola', 'insetos', 'Scarabaeidae', 'Coprófago', 'Cava galerias subterrâneas profundas para proteger sua fonte de alimento de outros insetoss.'),
('Besouro Caminhador Anactus', 'Anactus edentulus', 'insetos', 'Scarabaeidae', 'Detritívoro', 'Usa seu exoesqueleto espesso para resistir à dessecação sob o sol escaldante.'),
('Besouro Caracol Carcaju', 'Cychrus caraboides', 'insetos', 'Carabidae', 'Carnívoro', 'Suas mandíbulas estreitas são perfeitamente adaptadas para extrair lesmas de dentro de suas conchas.'),
('Besouro Terrestre Coriáceo', 'Carabus coriaceus', 'insetos', 'Carabidae', 'Carnívoro', 'Um dos maiores Besouros terrestres da Europa, incapaz de voar devido aos élitros soldados.'),
('Besouro Cego das Cavernas', 'Anophthalmus hitleri', 'insetos', 'Carabidae', 'Carnívoro', 'Vivendo na mais completa escuridão, perdeu os olhos e a pigmentação ao longo da evolução.'),
('Besouro Pedregal Gigante', 'Anthia thoracic', 'insetos', 'Carabidae', 'Carnívoro', 'Possui glândulas de defesa potentes capazes de cuspir substâncias irritantes a distâncias curtas.'),
('Besouro Corredor Ibérico', 'Carabus rugosus', 'insetos', 'Carabidae', 'Carnívoro', 'Possui coloração escura fosca que ajuda na absorção rápida de calor nas manhãs frias.'),
('Besouro Escavador Sombrio', 'Scarites buparius', 'insetos', 'Carabidae', 'Carnívoro', 'Passa o dia escondido sob pedras grandes, saindo apenas na penumbra para caçar.'),
('Besouro Devorador de Lesmas', 'Carabus nemoralis', 'insetos', 'Carabidae', 'Carnívoro', 'Aliado natural dos agricultores por controlar populações de moluscos pragas em hortas.'),
('Besouro Tigre Sem Asas', 'Manticora imperator', 'insetos', 'Carabidae', 'Carnívoro', 'Um predador voraz e robusto de savanas secas, caçando com investidas rápidas e agressivas.'),
('Besouro Predador de Oito Pontos', 'Anthia sexguttata', 'insetos', 'Carabidae', 'Carnívoro', 'Exibe marcações chamativas em seu corpo para alertar predadores sobre sua toxicidade.'),
('Besouro Terrestre Dourado', 'Carabus auratus', 'insetos', 'Carabidae', 'Carnívoro', 'Brilha com tons metálicos iridescentes quando exposto à luz direta do sol.'),
('Louva a Deus Orquídea', 'Hymenopus coronatus', 'insetos', 'Hymenopodidae', 'Carnívoro', 'Mimiciza perfeitamente uma flor de orquídea para atrair polinizadores inocentes direto para seu bote.'),
('Borboleta monarca', 'Danaus plexippus', 'insetos', 'Nymphalidae', 'Herbívoro', 'Famosa por sua migração multigeracional de milhares de quilômetros entre a América do Norte e o México.'),
('Abelha europeia', 'Apis mellifera', 'insetos', 'Apidae', 'Nectarívoro', 'Fundamental para a polinização de cultivos agrícolas e produção global de mel.'),
('Formiga cortadeira', 'Atta cephalotes', 'insetos', 'Formicidae', 'Herbívoro', 'Cortam pedaços de folhas para cultivar o fungo subterrâneo que serve de alimento para a colônia.'),
('Libélula azul', 'Anax imperator', 'insetos', 'Aeshnidae', 'Carnívoro', 'Ágil predadora aérea com uma taxa de sucesso de captura de presas superior a %.'),
('Joaninha de Sete Pontos', 'Coccinella septempunctata', 'insetos', 'Coccinellidae', 'Carnívoro', 'insetos benéfico que consome vorazmente pulgões nas plantações.'),
('Gafanhoto migratório', 'Locusta migratoria', 'insetos', 'Acrididae', 'Herbívoro', 'Capaz de se reunir em grandes enxames destrutivos que devastam plantações inteiras.'),
('Vaga lume Comum', 'Photinus pyralis', 'insetos', 'Lampyridae', 'Carnívoro', 'Produz luz fria através de bioluminescência abdominal para atrair parceiros sexuais.'),
('Bicho pau Gigante', 'Extatosoma tiaratum', 'insetos', 'Phasmatidae', 'Herbívoro', 'Mestre supremo da camuflagem que se parece perfeitamente com folhas secas e espinhosas.'),
('Cigarra comum', 'Lyristes plebejus', 'insetos', 'Cicadidae', 'Herbívoro', 'Emite um som estridente característico através de membranas chamadas timbales.'),
('Mariposa luna', 'Actias luna', 'insetos', 'Saturniidae', 'Herbívoro', 'Mariposa noturna de coloração verde translúcida que não possui boca na fase adulta.'),
('Mosca varejeira', 'Calliphora vicina', 'insetos', 'Calliphoridae', 'Detritívoro', 'Importante na decomposição de matéria orgânica e em investigações forenses.'),
('Percevejo verde', 'Nezara viridula', 'insetos', 'Pentatomidae', 'Herbívoro', 'Libera um odor defensivo forte e desagradável quando ameaçado ou manuseado.'),
('Tesourinha comum', 'Forficula auricularia', 'insetos', 'Forficulidae', 'Omnívoro', 'Reconhecida pelos cercos em forma de pinça na extremidade do abdome.'),
('Louva deus comum', 'Mantis religiosa', 'insetos', 'Mantidae', 'Carnívoro', 'Predador de emboscada paciente com excelente visão estereoscópica.'),
('Abelha carpintaria', 'Xylocopa virginica', 'insetos', 'Apidae', 'Nectarívoro', 'Fura a madeira para construir seus ninhos em galerias complexas.'),
('Pulga dos gatos', 'Ctenocephalides felis', 'insetos', 'Pulicidae', 'Hematófago', 'Ectoparasita sem asas capaz de saltar dezenas de vezes o seu próprio comprimento.'),
('Barata americana', 'Periplaneta americana', 'insetos', 'Blattidae', 'Detritívoro', 'insetos noturno extremamente resistente e rápido, adaptado a ambientes urbanos.'),
('Cupim subterrâneo', 'Coptotermes formosanus', 'insetos', 'Rhinotermitidae', 'Herbívoro', 'Vive em colônias complexas com castas especializadas e consome celulose de madeira.'),
('Vespa mandarina', 'Vespa mandarinia', 'insetos', 'Vespidae', 'Carnívoro', 'A maior espécie de vespa do mundo, conhecida por ataques devastadores a colmeias de abelhas.'),
('insetos folha', 'Phyllium bioculatum', 'insetos', 'Phylliidae', 'Herbívoro', 'Mimetiza folhas verdes com veias e texturas tão perfeitas que enganam predadores visuais.'),

('Caranguejeira Rosa', 'Grammostola rosea', 'Aracnídeos', 'Theraphosidae', 'Carnívoro', 'Aranha dócil nativa do Chile.'),
('Aranha Golias', 'Theraphosa blondi', 'Aracnídeos', 'Theraphosidae', 'Carnívoro', 'A maior aranha do mundo.'),
('Tarântula de Joelhos Vermelhos', 'Brachypelma smithi', 'Aracnídeos', 'Theraphosidae', 'Carnívoro', 'Famosa pelas listras laranjas.'),
('Viúva Negra', 'Latrodectus mactans', 'Aracnídeos', 'Theridiidae', 'Carnívoro', 'Veneno neurotóxico potente.'),
('Aranha Marrom', 'Loxosceles reclusa', 'Aracnídeos', 'Sicariidae', 'Carnívoro', 'Veneno necrosante perigoso.'),
('Armadeira', 'Phoneutria nigriventer', 'Aracnídeos', 'Ctenidae', 'Carnívoro', 'Agressiva e venenosa.'),
('Aranha Saltadora Zebra', 'Salticus scenicus', 'Aracnídeos', 'Salticidae', 'Carnívoro', 'Pula grandes distâncias.'),
('Aranha Pescadora', 'Dolomedes tenebrosus', 'Aracnídeos', 'Pisauridae', 'Carnívoro', 'Caça na superfície da água.'),
('Aranha Lobo', 'Lycosa tarantula', 'Aracnídeos', 'Lycosidae', 'Carnívoro', 'Caça correndo no solo.'),
('Aranha Caranguejo', 'Misumena vatia', 'Aracnídeos', 'Thomisidae', 'Carnívoro', 'Camufla se em flores.'),
('Escorpião Amarelo', 'Tityus serrulatus', 'Aracnídeos', 'Buthidae', 'Carnívoro', 'Muito perigoso no Brasil.'),
('Escorpião Imperador', 'Pandinus imperator', 'Aracnídeos', 'Scorpionidae', 'Carnívoro', 'Gigante de garras grossas.'),
('Escorpião Negro', 'Tityus bahiensis', 'Aracnídeos', 'Buthidae', 'Carnívoro', 'Tronco escuro e pernas claras.'),
('Escorpião Dourado', 'Leiurus quinquestriatus', 'Aracnídeos', 'Buthidae', 'Carnívoro', 'Veneno altamente letal.'),
('Escorpião do Deserto', 'Hadrurus arizonensis', 'Aracnídeos', 'Caraboctonidae', 'Carnívoro', 'O maior da América do Norte.'),
('Carrapato Estrela', 'Amblyomma cajennense', 'Aracnídeos', 'Ixodidae', 'Hematófago', 'Transmite febre maculosa.'),
('Carrapato de Boi', 'Rhipicephalus microplus', 'Aracnídeos', 'Ixodidae', 'Hematófago', 'Praga na pecuária.'),
('Ácaro da Poeira', 'Dermatophagoides pteronyssinus', 'Aracnídeos', 'Pyroglyphidae', 'Detritívoro', 'Vive em colchões.'),
('Ácaro da Sarna', 'Sarcoptes scabiei', 'Aracnídeos', 'Sarcoptidae', 'Parasita', 'Escava a pele humana.'),
('Ácaro Vermelho', 'Trombidium holosericeum', 'Aracnídeos', 'Trombidiidae', 'Carnívoro', 'Pelagem vermelha aveludada.'),
('Opilião Comum', 'Phalangium opilio', 'Aracnídeos', 'Phalangiidae', 'Onívoro', 'Pernas muito finas e longas.'),
('Opilião Espinhoso', 'Acanthopachylus aculeatus', 'Aracnídeos', 'Gonyleptidae', 'Onívoro', 'Possui espinhos defensivos.'),
('Opilião Cavernícola', 'Gongylobelus sp.', 'Aracnídeos', 'Gongyleptidae', 'Onívoro', 'Vive em cavernas escuras.'),
('Opilião Laranja', 'Vonones sayi', 'Aracnídeos', 'Cosmetidae', 'Onívoro', 'Cor chamativa e odor forte.'),
('Amblipígio Gigante', 'Acanthophrynus coronatus', 'Aracnídeos', 'Phrynidae', 'Carnívoro', 'Assustador, mas sem veneno.'),
('Aranha Chicote', 'Phrynus marginemaculatus', 'Aracnídeos', 'Phrynidae', 'Carnívoro', 'Usa pernas como antenas.'),
('Aranha Camelo', 'Galeodes arabs', 'Aracnídeos', 'Galeodidae', 'Carnívoro', 'Corre rápido no deserto.'),
('Vinagrinho', 'Mastigoproctus giganteus', 'Aracnídeos', 'Thelyphonidae', 'Carnívoro', 'Dispara ácido acético.'),
('Aranha Teia de Funil', 'Atrax robustus', 'Aracnídeos', 'Atracidae', 'Carnívoro', 'Mortal da Austrália.'),
('Tarântula Azul', 'Cyriopagopus lividus', 'Aracnídeos', 'Theraphosidae', 'Carnívoro', 'Pernas de azul brilhante.'),
('Tarântula Metálica', 'Poecilotheria metallica', 'Aracnídeos', 'Theraphosidae', 'Carnívoro', 'Arborícola ameaçada.'),
('Aranha Espinhosa', 'Gasteracantha cancriformis', 'Aracnídeos', 'Araneidae', 'Carnívoro', 'Abdômen com espinhos.'),
('Aranha de Jardim', 'Argiope aurantia', 'Aracnídeos', 'Araneidae', 'Carnívoro', 'Teia em formato de zig zag.'),
('Caranguejeira Baboon', 'Pelinobius muticus', 'Aracnídeos', 'Theraphosidae', 'Carnívoro', 'Cava tocas no Quênia.'),
('Escorpião de Cauda Grossa', 'Androctonus australis', 'Aracnídeos', 'Buthidae', 'Carnívoro', 'Letal do norte da África.'),
('Escorpião de Casca', 'Centruroides sculpturatus', 'Aracnídeos', 'Buthidae', 'Carnívoro', 'Escala paredes.'),
('Pseudoescorpião', 'Chelifer cancroides', 'Aracnídeos', 'Cheliferidae', 'Carnívoro', 'Come ácaros em livros antigos.'),
('Palpígrado', 'Eukoenenia mirabilis', 'Aracnídeos', 'Eukoeneniidae', 'Carnívoro', 'Micro aracnídeo de solo.'),
('Carrapato de Cervo', 'Ixodes scapularis', 'Aracnídeos', 'Ixodidae', 'Hematófago', 'Vetor da doença de Lyme.'),
('Ácaro Aranha', 'Tetranychus urticae', 'Aracnídeos', 'Tetranychidae', 'Herbívoro', 'Praga agrícola que tece teias.'),
('Ricínuleo', 'Ricinoides atewa', 'Aracnídeos', 'Ricinoididae', 'Carnívoro', 'Parece um carrapato blindado.'),
('Solífugo Dourado', 'Eremobates pallipes', 'Aracnídeos', 'Eremobatidae', 'Carnívoro', 'Caça lagartos à noite.'),
('Aranha Espadachim', 'Dysdera crocata', 'Aracnídeos', 'Dysderidae', 'Carnívoro', 'Caçadora de tatuzinhos.'),
('Aranha Cuspidora', 'Scytodes thoracica', 'Aracnídeos', 'Scytodidae', 'Carnívoro', 'Cospe teia venenosa.'),
('Tarântula Tigre', 'Poecilotheria tigrinawesseli', 'Aracnídeos', 'Theraphosidae', 'Carnívoro', 'Padrão listrado.'),
('Escorpião Listrado', 'Centruroides vittatus', 'Aracnídeos', 'Buthidae', 'Carnívoro', 'Comum no Texas.'),
('Caranguejeira Veludo Negro', 'Grammostola pulchra', 'Aracnídeos', 'Theraphosidae', 'Carnívoro', 'Totalmente preta e mansa.'),
('Tarântula Esqueleto', 'Ephebopus murinus', 'Aracnídeos', 'Theraphosidae', 'Carnívoro', 'Pernas lembram ossos.'),
('Caranguejeira Caranguejo', 'Acanthoscurria geniculata', 'Aracnídeos', 'Theraphosidae', 'Carnívoro', 'Faixas brancas nas pernas.'),
('Opilião Lenhador', 'Leiobunum rotundum', 'Aracnídeos', 'Sclerosomatidae', 'Onívoro', 'Aglomera se em troncos.'),
('Ácaro de Foliculo', 'Demodex folliculorum', 'Aracnídeos', 'Demodicidae', 'Detritívoro', 'Vive nos poros do rosto.'),
('Carrapato de Galinha', 'Argas persicus', 'Aracnídeos', 'Argasidae', 'Hematófago', 'Carrapato mole de aves.'),
('Opilião Gigante', 'Trogulus tricarinatus', 'Aracnídeos', 'Trogulidae', 'Onívoro', 'Cobre se de terra.'),
('Aranha d Água', 'Argyroneta aquatica', 'Aracnídeos', 'Cybaeidae', 'Carnívoro', 'Constrói sino de ar embaixo d água.'),
('Aranha Lince', 'Peucetia viridans', 'Aracnídeos', 'Oxyopidae', 'Carnívoro', 'Pernas cheias de espinhos.'),
('Aranha Caçadora', 'Heteropoda venatoria', 'Aracnídeos', 'Sparassidae', 'Carnívoro', 'Gigante e rápida nas paredes.'),
('Aranha Gladiadora', 'Deinopis subrufa', 'Aracnídeos', 'Deinopidae', 'Carnívoro', 'Joga a teia como uma rede.'),
('Escorpião de Caverna', 'Typhlochactas mitchelli', 'Aracnídeos', 'Typhlochactidae', 'Carnívoro', 'Cego e vive nas trevas.'),
('Amblipígio das Cavernas', 'Charinus cavernicolus', 'Aracnídeos', 'Charinidae', 'Carnívoro', 'Totalmente cego.'),
('Solífugo Gigante', 'Solpuga venosa', 'Aracnídeos', 'Solpugidae', 'Carnívoro', 'Mordida dilacera presas.'),
('Aranha de Pelúcia', 'Eresus sandaliatus', 'Aracnídeos', 'Eresidae', 'Carnívoro', 'Macho vermelho com pintas pretas.'),

('Caranguejo Ermitão', 'Pagurus bernhardus', 'Crustáceos', 'Paguridae', 'Detritívoro', 'Mora em conchas vazias.'),
('Caranguejo Aranha Gigante', 'Macrocheira kaempferi', 'Crustáceos', 'Inachidae', 'Onívoro', 'O maior artrópode do mundo.'),
('Caranguejo Uçá', 'Ucides cordatus', 'Crustáceos', 'Ucididae', 'Herbívoro', 'Vive nos manguezais do Brasil.'),
('Siri Azul', 'Callinectes sapidus', 'Crustáceos', 'Portunidae', 'Onívoro', 'Possui nadadeiras traseiras fortes.'),
('Caranguejo Fantasma', 'Ocypode quadrata', 'Crustáceos', 'Ocypodidae', 'Detritívoro', 'Corre muito rápido na areia.'),
('Lagosta Suada', 'Panulirus argus', 'Crustáceos', 'Palinuridae', 'Carnívoro', 'Não possui pinças grandes.'),
('Lagosta Americana', 'Homarus americanus', 'Crustáceos', 'Nephropidae', 'Carnívoro', 'Garras esmagadoras gigantes.'),
('Camarão Limpador', 'Lysmata amboinensis', 'Crustáceos', 'Hippolytidae', 'Onívoro', 'Limpa parasitas de peixes.'),
('Camarão Pistola', 'Alpheus heterochaelis', 'Crustáceos', 'Alpheidae', 'Carnívoro', 'Gera bolha sônica que atordoa.'),
('Tamarutaca', 'Odontodactylus scyllarus', 'Crustáceos', 'Odontodactylidae', 'Carnívoro', 'Soco mais rápido do oceano.'),
('Tatuzinho de Jardim', 'Armadillidium vulgare', 'Crustáceos', 'Armadillidiidae', 'Detritívoro', 'Enrola se como uma bola.'),
('Isópode Gigante', 'Bathynomus giganteus', 'Crustáceos', 'Cirolanidae', 'Detritívoro', 'Devorador do fundo do mar.'),
('Craca Bolota', 'Balanus glandula', 'Crustáceos', 'Balanidae', 'Filtrador', 'Gruda em rochas e navios.'),
('Krill Antártico', 'Euphausia superba', 'Crustáceos', 'Euphausiidae', 'Filtrador', 'Base da teia alimentar do gelo.'),
('Caranguejo dos Coqueiros', 'Birgus latro', 'Crustáceos', 'Coenobitidae', 'Onívoro', 'Sobe em árvores e quebra cocos.'),
('Camarão Rosa', 'Penaeus paulensis', 'Crustáceos', 'Penaeidae', 'Detritívoro', 'Muito consumido na culinária.'),
('Caranguejo Chama Maré', 'Uca pugnax', 'Crustáceos', 'Ocypodidae', 'Detritívoro', 'Macho tem uma garra gigante.'),
('Caranguejo Yeti', 'Kiwa hirsuta', 'Crustáceos', 'Kiwaidae', 'Carnívoro', 'Garras peludas no fundo do mar.'),
('Lagosta Boxeadora', 'Enoplometopus debelius', 'Crustáceos', 'Enoplometopidae', 'Carnívoro', 'Pequena lagosta de recife.'),
('Camarão Imperador', 'Periclimenes imperator', 'Crustáceos', 'Palaemonidae', 'Onívoro', 'Pega carona em pepinos do mar.'),
('Siri Candeia', 'Portunus pelagicus', 'Crustáceos', 'Portunidae', 'Carnívoro', 'Siri nadador muito ágil.'),
('Lagostim Vermelho', 'Procambarus clarkii', 'Crustáceos', 'Cambaridae', 'Onívoro', 'Lagostim de água doce resistente.'),
('Camarão Bailarino', 'Rhynchocinetes durbanensis', 'Crustáceos', 'Rhynchocinetidae', 'Detritívoro', 'Movimento de dança na água.'),
('Pulga da Areia', 'Talitrus saltator', 'Crustáceos', 'Talitridae', 'Detritívoro', 'Pula nas praias à noite.'),
('Copépode Comum', 'Calanus finmarchicus', 'Crustáceos', 'Calanidae', 'Filtrador', 'Microcrustáceo planctônico.'),
('Caranguejo Decorador', 'Camposcia retusa', 'Crustáceos', 'Inachidae', 'Onívoro', 'Cola algas no corpo para camuflagem.'),
('Caranguejo Vampiro', 'Geosesarma dennerle', 'Crustáceos', 'Sesarmidae', 'Carnívoro', 'Cores roxas e olhos amarelos.'),
('Baratinha da Praia', 'Ligia oceanica', 'Crustáceos', 'Ligiidae', 'Detritívoro', 'Corre pelas pedras na maré baixa.'),
('Camarão Arlequim', 'Hymenocera picta', 'Crustáceos', 'Hymenoceridae', 'Carnívoro', 'Caça exclusivamente estrelas do mar.'),
('Percebe', 'Pollicipes pollicipes', 'Crustáceos', 'Pollicipedidae', 'Filtrador', 'Craca com pedúnculo comestível.'),
('Caranguejo Caleidoscópio', 'Gecarcoidea natalis', 'Crustáceos', 'Gecarcinidae', 'Herbívoro', 'Faz a marcha vermelha em Christmas Island.'),
('Camarão de Poça', 'Palaemon serratus', 'Crustáceos', 'Palaemonidae', 'Onívoro', 'Transparente com listras.'),
('Caranguejo Boxeador', 'Lybia tessellata', 'Crustáceos', 'Xanthidae', 'Onívoro', 'Segura anêmonas nas garras para defesa.'),
('Lagosta Sapateira', 'Scyllarides latus', 'Crustáceos', 'Scyllaridae', 'Onívoro', 'Sem garras, formato achatado.'),
('Siri da Lama', 'Scylla serrata', 'Crustáceos', 'Portunidae', 'Carnívoro', 'Vive enterrado no lodo.'),
('Caranguejo Fiddler', 'Uca tangeri', 'Crustáceos', 'Ocypodidae', 'Detritívoro', 'Agita a garra para cortejar.'),
('Isópode da Madeira', 'Porcellio scaber', 'Crustáceos', 'Porcellionidae', 'Detritívoro', 'Vive embaixo de troncos podres.'),
('Lagostim Azul', 'Cherax destructor', 'Crustáceos', 'Parastacidae', 'Onívoro', 'Garras fortes e cor azulada.'),
('Artêmia', 'Artemia salina', 'Crustáceos', 'Artemiidae', 'Filtrador', 'Sobrevive em lagos super salgados.'),
('Pulga d Água', 'Daphnia pulex', 'Crustáceos', 'Daphniidae', 'Filtrador', 'Nativa de águas doces paradas.'),
('Camarão Sangue', 'Lysmata debelius', 'Crustáceos', 'Hippolytidae', 'Onívoro', 'Vermelho forte com pintas brancas.'),
('Caranguejo Azul Terrestre', 'Cardisoma guanhumi', 'Crustáceos', 'Gecarcinidae', 'Herbívoro', 'Escava tocas na restinga.'),
('Caranguejo Dourado', 'Chaceon fenneri', 'Crustáceos', 'Geryonidae', 'Carnívoro', 'Vive em grandes profundidades.'),
('Lagosta de Água Doce', 'Astacus astacus', 'Crustáceos', 'Astacidae', 'Onívoro', 'Espécie europeia ameaçada.'),
('Caranguejo Rei', 'Paralithodes camtschaticus', 'Crustáceos', 'Lithodidae', 'Carnívoro', 'Altamente comercializado no Alasca.'),
('Camarão Bambu', 'Atyopsis moluccensis', 'Crustáceos', 'Atyidae', 'Filtrador', 'Usa patas em forma de leque para filtrar água.'),
('Caranguejo Japonês', 'Chionoecetes opilio', 'Crustáceos', 'Oregoniidae', 'Onívoro', 'Caranguejo das neves.'),
('Caranguejo Aranha Decorador', 'Oregonia gracilis', 'Crustáceos', 'Oregoniidae', 'Onívoro', 'Parece uma alga andante.'),
('Craca Gigante', 'Austromegabalanus psittacus', 'Crustáceos', 'Balanidae', 'Filtrador', 'Comestível na costa chilena.'),
('Isópode Parasita', 'Cymothoa exigua', 'Crustáceos', 'Cymothoidae', 'Parasita', 'Substitui a língua de peixes.'),
('Lagosta Pintada', 'Panulirus versicolor', 'Crustáceos', 'Palinuridae', 'Carnívoro', 'Coloração vibrante em recifes.'),
('Siri Boia', 'Arenaeus cribrarius', 'Crustáceos', 'Portunidae', 'Carnívoro', 'Comum em praias brasileiras.'),
('Caranguejo Pedra', 'Menippe mercenaria', 'Crustáceos', 'Menippidae', 'Carnívoro', 'Possui pinças esmagadoras massivas.'),
('Camarão Tigre Gigante', 'Penaeus monodon', 'Crustáceos', 'Penaeidae', 'Detritívoro', 'Muito criado em cativeiro.'),
('Camarão Sete Barbas', 'Xiphopenaeus kroyeri', 'Crustáceos', 'Penaeidae', 'Detritívoro', 'Comum no litoral sudeste brasileiro.'),
('Caranguejo de Galápagos', 'Grapsus grapsus', 'Crustáceos', 'Grapsidae', 'Herbívoro', 'Colorido e anda pelas pedras vulcânicas.'),
('Camarão Fantasma', 'Palaemonetes paludosus', 'Crustáceos', 'Palaemonidae', 'Detritívoro', 'Totalmente transparente.'),
('Lagosta de Lama', 'Thalassina anomala', 'Crustáceos', 'Thalassinidae', 'Detritívoro', 'Constrói montes de lama no mangue.'),
('Caranguejo Bola', 'Ilia nucleus', 'Crustáceos', 'Leucosiidae', 'Detritívoro', 'Carapaça perfeitamente esférica.'),
('Anfípode Cego', 'Niphargus', 'Crustáceos', 'Niphargidae', 'Onívoro', 'Vive em lençóis freáticos.'),
('Camarão Nariz de Agulha', 'Farfantepenaeus subtilis', 'Crustáceos', 'Penaeidae', 'Detritívoro', 'Possui rostro alongado.'),

('Caracol de Jardim', 'Cornu aspersum', 'Moluscos', 'Helicidae', 'Herbívoro', 'Deixa um rastro de muco por onde passa.'),
('Caramujo Gigante Africano', 'Lissachatina fulica', 'Moluscos', 'Achatinidae', 'Herbívoro', 'Praga invasora devoradora de hortas.'),
('Polvo Comum', 'Octopus vulgaris', 'Moluscos', 'Octopodidae', 'Carnívoro', 'Extremamente inteligente e mestre em camuflagem.'),
('Lula Colossal', 'Mesonychoteuthis hamiltoni', 'Moluscos', 'Cranchiidae', 'Carnívoro', 'Possui ganchos nos tentáculos.'),
('Lula Gigante', 'Architeuthis dux', 'Moluscos', 'Architeuthidae', 'Carnívoro', 'O olho é do tamanho de um prato.'),
('Ostra do Pacífico', 'Magallana gigas', 'Moluscos', 'Ostreidae', 'Filtrador', 'Cultivada no mundo todo para consumo.'),
('Mexilhão Dourado', 'Limnoperna fortunei', 'Moluscos', 'Mytilidae', 'Filtrador', 'Invasor de rios sul americanos.'),
('Náutilo', 'Nautilus pompilius', 'Moluscos', 'Nautilidae', 'Carnívoro', 'Fóssil vivo com concha em espiral.'),
('Choco', 'Sepia officinalis', 'Moluscos', 'Sepiidae', 'Carnívoro', 'Possui osso interno e muda de textura.'),
('Polvo de Anéis Azuis', 'Hapalochlaena maculosa', 'Moluscos', 'Octopodidae', 'Carnívoro', 'Pequeno mas com veneno mortal.'),
('Polvo Mímico', 'Thaumoctopus mimicus', 'Moluscos', 'Octopodidae', 'Carnívoro', 'Imita peixes venenosos e serpentes.'),
('Polvo Dumbo', 'Grimpoteuthis', 'Moluscos', 'Opisthoteuthidae', 'Carnívoro', 'Nadas com abas que lembram orelhas.'),
('Lesma do Mar Dragão Azul', 'Glaucus atlanticus', 'Moluscos', 'Glaucidae', 'Carnívoro', 'Flutua de cabeça para baixo comendo caravelas.'),
('Bailarina Espanhola', 'Hexabranchus sanguineus', 'Moluscos', 'Hexabranchidae', 'Carnívoro', 'Nada ondulando feito uma saia flamenca.'),
('Lesma Leopardo', 'Limax maximus', 'Moluscos', 'Limacidae', 'Onívoro', 'Acasala pendurada por um fio de muco.'),
('Caracol Cone', 'Conus geographus', 'Moluscos', 'Conidae', 'Carnívoro', 'Dispara um arpão de veneno fatal.'),
('Lula Vampira', 'Vampyroteuthis infernalis', 'Moluscos', 'Vampyroteuthidae', 'Detritívoro', 'Vira do avesso para se proteger.'),
('Marisco', 'Mytilus edulis', 'Moluscos', 'Mytilidae', 'Filtrador', 'Comum em costões rochosos.'),
('Vieira', 'Pecten maximus', 'Moluscos', 'Pectinidae', 'Filtrador', 'Foge nadando abrindo e fechando a concha.'),
('Ostra Perlífera', 'Pinctada margaritifera', 'Moluscos', 'Pteriidae', 'Filtrador', 'Produz pérolas negras valiosas.'),
('Berbigão', 'Cerastoderma edule', 'Moluscos', 'Cardiidae', 'Filtrador', 'Vive enterrado na areia de praias.'),
('Caramujo Trombeta', 'Charonia tritonis', 'Moluscos', 'Charoniidae', 'Carnívoro', 'Predador da estrela do mar coroa de espinhos.'),
('Polvo do Coco', 'Amphioctopus marginatus', 'Moluscos', 'Octopodidae', 'Carnívoro', 'Usa cascas de coco como escudo.'),
('Aruá do Mato', 'Megalobulimus', 'Moluscos', 'Megalobulimidae', 'Herbívoro', 'Caracol nativo gigante das florestas brasileiras.'),
('Caramujo Maçã', 'Pomacea maculata', 'Moluscos', 'Ampullariidae', 'Herbívoro', 'Bota ovos rosas fora da água.'),
('Lesma do Mar Ovelhinha', 'Costasiella kuroshimae', 'Moluscos', 'Costasiellidae', 'Herbívoro', 'Faz fotossíntese com algas que engole.'),
('Lula Voadora', 'Todarodes pacificus', 'Moluscos', 'Ommastrephidae', 'Carnívoro', 'Salta para fora da água planar longas distâncias.'),
('Siba Chocante', 'Metasepia pfefferi', 'Moluscos', 'Sepiidae', 'Carnívoro', 'Anda pelo fundo do mar e exibe cores pulsantes.'),
('Búzio', 'Bulla striata', 'Moluscos', 'Bullidae', 'Herbívoro', 'Concha lisa comum em colares.'),
('Caramujo de Aquário', 'Neritina natalensis', 'Moluscos', 'Neritidae', 'Herbívoro', 'Excelente devorador de algas em vidros.'),
('Argonauta', 'Argonauta argo', 'Moluscos', 'Argonautidae', 'Carnívoro', 'Fêmea cria uma concha fina para ovos.'),
('Lula de Vidro', 'Cranchia scabra', 'Moluscos', 'Cranchiidae', 'Carnívoro', 'Totalmente transparente para sumir na luz.'),
('Chiton', 'Chiton tuberculatus', 'Moluscos', 'Chitonidae', 'Herbívoro', 'Concha feita de placas sobrepostas.'),
('Lesma do Mar Pikachu', 'Thecacera pacifica', 'Moluscos', 'Polyceridae', 'Carnívoro', 'Amarela com pontas pretas.'),
('Bivalve Gigante', 'Tridacna gigas', 'Moluscos', 'Cardiidae', 'Filtrador', 'Pode pesar kg nos recifes de coral.'),
('Bredo', 'Ensis directus', 'Moluscos', 'Pharidae', 'Filtrador', 'Concha reta como uma navalha.'),
('Lesma Banana', 'Ariolimax columbianus', 'Moluscos', 'Ariolimacidae', 'Herbívoro', 'Amarela brilhante das florestas úmidas.'),
('Caracol Assassino', 'Clea helena', 'Moluscos', 'Buccinidae', 'Carnívoro', 'Usado em aquários para comer outros caracóis.'),
('Ostra do Mangue', 'Crassostrea rhizophorae', 'Moluscos', 'Ostreidae', 'Filtrador', 'Gruda nas raízes do mangue.'),
('Caracol de Fogo', 'Platymma tweediei', 'Moluscos', 'Chronidae', 'Onívoro', 'Corpo vermelho vibrante e concha preta.'),
('Polvo Pigmeu', 'Octopus wolfi', 'Moluscos', 'Octopodidae', 'Carnívoro', 'O menor polvo conhecido.'),
('Lula Lagalume', 'Watasenia scintillans', 'Moluscos', 'Enoploteuthidae', 'Carnívoro', 'Brilha forte no escuro para atrair presas.'),
('Pé de Pelicano', 'Aporrhais pespelecani', 'Moluscos', 'Aporrhaidae', 'Onívoro', 'Concha com pontas que lembram patas.'),
('Concha da Lua', 'Polinices', 'Moluscos', 'Naticidae', 'Carnívoro', 'Perfura outras conchas com ácido.'),
('Lesma do mar Alface', 'Elysia crispata', 'Moluscos', 'Plakobranchidae', 'Herbívoro', 'Corpo ondulado que rouba cloroplastos.'),
('Escafópode', 'Antalis vulgaris', 'Moluscos', 'Dentaliidae', 'Detritívoro', 'Concha em forma de dente de elefante.'),
('Polvo Cobertor', 'Tremoctopus violaceus', 'Moluscos', 'Tremoctopodidae', 'Carnívoro', 'Abre uma grande rede de pele para intimidar.'),
('Sépia Faraó', 'Sepia pharaonis', 'Moluscos', 'Sepiidae', 'Carnívoro', 'Textura e cor espetaculares.'),
('Caracol Terrestre Ibérico', 'Otala lactea', 'Moluscos', 'Helicidae', 'Herbívoro', 'Consumido como escargot.'),
('Abre Fecha', 'Spondylus', 'Moluscos', 'Spondylidae', 'Filtrador', 'Concha cheia de espinhos longos.'),
('Lula de Humboldt', 'Dosidicus gigas', 'Moluscos', 'Ommastrephidae', 'Carnívoro', 'Agressiva e caça em grandes bandos.'),
('Caramujo de Areia', 'Nassarius', 'Moluscos', 'Nassariidae', 'Detritívoro', 'Sai da areia quando sente cheiro de carniça.'),
('Búzios Cobra', 'Cypraea tigris', 'Moluscos', 'Cypraeidae', 'Onívoro', 'Concha super polida com pintas.'),
('Polvo das Fontes Termais', 'Vulcanoctopus hydrothermalis', 'Moluscos', 'Octopodidae', 'Carnívoro', 'Vive perto de vulcões submarinos.'),
('Mexilhão Zebra', 'Dreissena polymorpha', 'Moluscos', 'Dreissenidae', 'Filtrador', 'Grave praga de dutos industriais.'),
('Lesma Nua', 'Deroceras reticulatum', 'Moluscos', 'Agriolimacidae', 'Herbívoro', 'Praga agrícola que devora mudas.'),
('Nudibrânquio Pijama', 'Chromodoris quadricolor', 'Moluscos', 'Chromodorididae', 'Carnívoro', 'Listras azuis, brancas e laranjas.'),
('Caracol Pintado', 'Liguus fasciatus', 'Moluscos', 'Orthalicidae', 'Herbívoro', 'Conchas coloridas arborícolas da Flórida.'),
('Teredo', 'Teredo navalis', 'Moluscos', 'Teredinidae', 'Xilófago', 'Cupim do mar, fura cascos de madeira.'),
('Anjo do Mar', 'Clione limacina', 'Moluscos', 'Clionidae', 'Carnívoro', 'Molusco pelágico transparente que parece flutuar com asas.'),
('Caramujo Babosa', 'Physella acuta', 'Moluscos', 'Physidae', 'Detritívoro', 'Caramujo de água doce comum em aquários.'),

('Água viva da lua', 'Aurelia aurita', 'Cnidário', 'Ulmaridae', 'Carnívoro', 'Possui quatro braços orais transparentes e um formato de guarda chuva com margens tentaculares.'),
('Caravela portuguesa', 'Physalia physalis', 'Cnidário', 'Physaliidae', 'Carnívoro', 'Organismo colonial flutuante com tentáculos longos e altamente venenosos.'),
('Anêmona do mar comum', 'Actinia equina', 'Cnidário', 'Actiniidae', 'Carnívoro', 'Fixa se a rochas costeiras e retrai seus tentáculos vermelhos quando exposta à maré baixa.'),
('Água viva juba de leão', 'Cyanea capillata', 'Cnidário', 'Cyaneidae', 'Carnívoro', 'A maior espécie de água viva do mundo, com centenas de tentáculos finos e longos.'),
('Coral cérebro', 'Meandrina meandrites', 'Cnidário', 'Meandrinidae', 'Carnívoro', 'Coral construtor de recifes com sulcos sinuosos que lembram a textura de um cérebro.'),
('Vespa do mar', 'Chironex fleckeri', 'Cnidário', 'Chirodropidae', 'Carnívoro', 'Uma das criaturas mais venenosas do planeta, encontrada nas águas costeiras do Indo Pacífico.'),
('Hydra verde', 'Hydra viridissima', 'Cnidário', 'Hydridae', 'Carnívoro', 'Pequeno pólipo de água doce que vive fixo a vegetação aquática e possui simetria radial.'),
('Coral chifre de alce', 'Acropora palmata', 'Cnidário', 'Acroporidae', 'Carnívoro', 'Coral ramificado essencial para a proteção das costas contra tempestades tropicais.'),
('Anêmona gigante de carpetes', 'Stichodactyla gigantea', 'Cnidário', 'Stichodactylidae', 'Carnívoro', 'Abriga peixes palhaço em simbiose mútua contra predadores marinhos.'),
('Água viva de cabeça de cogumelo', 'Rhizostoma pulmo', 'Cnidário', 'Rhizostomatidae', 'Carnívoro', 'Frequente no Mar Mediterrâneo, alimenta se filtrando plâncton com seus braços fundidos.'),
('Coral fogo', 'Millepora alcicornis', 'Cnidário', 'Milleporidae', 'Carnívoro', 'Hidrocoral urticante que causa forte sensação de queimadura ao toque humano.'),
('Água viva luminosa', 'Pelagia noctiluca', 'Cnidário', 'Pelagiidae', 'Carnívoro', 'Emite forte luz azulada quando perturbada mecanicamente na escuridão do oceano.'),
('Caneta do mar', 'Pennatula phosphorea', 'Cnidário', 'Pennatulidae', 'Carnívoro', 'Colônia de pólipos que se assemelha a uma antiga pena de escrita fincada no sedimento.'),
('Coral sol', 'Tubastraea coccinea', 'Cnidário', 'Dendrophylliidae', 'Carnívoro', 'Espécie invasora no litoral brasileiro, reconhecida por seus pólipos de coloração amarela intensa.'),
('Anêmona sol', 'Condylactis gigantea', 'Cnidário', 'Actiniidae', 'Carnívoro', 'Exibe tentáculos longos com pontas bulbosas vibrantes que variam do verde ao roxo.'),
('Água viva imortal', 'Turritopsis dohrnii', 'Cnidário', 'Oceaniidae', 'Carnívoro', 'Capaz de reverter seu ciclo de vida celular após atingir a maturidade, teoricamente imortal.'),
('Coral mão de morto', 'Alcyonium digitatum', 'Cnidário', 'Alcyoniidae', 'Carnívoro', 'Coral mole de águas frias com lóbulos carnudos que lembram dedos humanos.'),
('Velella', 'Velella velella', 'Cnidário', 'Porpitidae', 'Carnívoro', 'Pequena colônia flutuante dotada de uma crista triangular que atua como vela ao vento.'),
('Anêmona tubo', 'Cerianthus membranaceus', 'Cnidário', 'Cerianthidae', 'Carnívoro', 'Constrói um tubo membranoso no sedimento arenoso de onde projeta seus longos tentáculos.'),
('Coral cogumelo', 'Fungia fungites', 'Cnidário', 'Fungiidae', 'Carnívoro', 'Coral solitário em forma de disco que descansa livremente sobre o substrato arenoso.'),
('Água viva caçadora', 'Chiropsalmus quadrumana', 'Cnidário', 'Chirodropidae', 'Carnívoro', 'Cubozoário com tentáculos dispostos em cachos nos cantos de sua umbrella cúbica.'),
('Coral preto', 'Antipathes dichotoma', 'Cnidário', 'Antipathidae', 'Carnívoro', 'Possui esqueleto córneo escuro muito utilizado historicamente na fabricação de joias.'),
('Anêmona verde gigante', 'Anthopleura xanthogrammica', 'Cnidário', 'Actiniidae', 'Carnívoro', 'Deve sua cor verde vibrante a algas fotossintéticas simbióticas que habitam seus tecidos.'),
('Água viva de ponto azul', 'Mastigias papua', 'Cnidário', 'Mastigiidae', 'Carnívoro', 'Abriga algas zooxantelas que lhe fornecem energia através da luz solar.'),
('Coral de fogo comum', 'Millepora complanata', 'Cnidário', 'Milleporidae', 'Carnívoro', 'Forma lâminas verticais calcárias em recifes rasos e expostos à forte arrebentação.'),
('Anêmona das rochas', 'Bunodosoma caissorum', 'Cnidário', 'Actiniidae', 'Carnívoro', 'Espécie comum no litoral brasileiro com verrugas adesivas pelo corpo.'),
('Água viva japonesa', 'Nemopilema nomurai', 'Cnidário', 'Stomolophidae', 'Carnívoro', 'Gigante dos mares asiáticos que causa enormes prejuízos à pesca comercial.'),
('Coral estrela', 'Montastraea cavernosa', 'Cnidário', 'Faviidae', 'Carnívoro', 'Forma colônias massivas com cálices profundos e bem demarcados na superfície.'),
('Anêmona elegante', 'Anthopleura elegantissima', 'Cnidário', 'Actiniidae', 'Carnívoro', 'Conhecida por formar colônias clonais que travam batalhas territoriais usando tentáculos especializados.'),
('Água viva crucifixe', 'Haliclystus auricula', 'Cnidário', 'Staurozoa', 'Carnívoro', 'Estauromedusa séssil que se fixa a algas marinhas por um pedúnculo basal.'),
('Coral tubular amarelo', 'Tubastraea micrantha', 'Cnidário', 'Dendrophylliidae', 'Carnívoro', 'Forma arbustos densos com ramificações escuras e pólipos amarelos brilhantes.'),
('Anêmona cavalo', 'Actinia fragacea', 'Cnidário', 'Actiniidae', 'Carnívoro', 'Apresenta manchas verdes distintas ao longo de sua base carnuda vermelha.'),
('Água viva bombardeira', 'Periphylla periphylla', 'Cnidário', 'Periphyllidae', 'Carnívoro', 'Espécie de profundidade com coloração marrom avermelhada escura e bioluminescência.'),
('Coral chifre de cervo falso', 'Acropora cervicornis', 'Cnidário', 'Acroporidae', 'Carnívoro', 'Crescimento rápido em forma de galhos cilíndricos pontiagudos.'),
('Anêmona borboleta', 'Aiptasia pallida', 'Cnidário', 'Aiptasiidae', 'Carnívoro', 'Comum em aquários marinhos, considerada praga devido à sua rápida proliferação clonal.'),
('Água viva diamante', 'Chirodropus pragmaticus', 'Cnidário', 'Chirodropidae', 'Carnívoro', 'Cubomedusa predadora com potentes toxinas neurotóxicas em seus tentáculos.'),
('Coral couve flor', 'Pocillopora damicornis', 'Cnidário', 'Pocilloporidae', 'Carnívoro', 'Possui ramificações curtas e compactas que lembram a cabeça de uma couve flor.'),
('Anêmona de fogo', 'Actinodendron arboreum', 'Cnidário', 'Actinodendridae', 'Carnívoro', 'Seus tentáculos lembram galhos de árvores e liberam toxinas severas ao toque.'),
('Água viva coroa', 'Atolla wyvillei', 'Cnidário', 'Atollidae', 'Carnívoro', 'Emite um impressionante show de luzes azuladas em anel quando atacada no abismo marinho.'),
('Coral abano do mar', 'Gorgonia ventalina', 'Cnidário', 'Gorgoniidae', 'Carnívoro', 'Gorgônia em formato de leque plano que se posiciona perpendicularmente às correntes.'),
('Anêmona magnífica', 'Heteractis magnifica', 'Cnidário', 'Stichodactylidae', 'Carnívoro', 'Uma das principais espécies hospedeiras para peixes palhaço em recifes tropicais.'),
('Água viva azul', 'Cyanea lamarckii', 'Cnidário', 'Cyaneidae', 'Carnívoro', 'Água viva translúcida com tons azulados encontrada nas águas temperadas europeias.'),
('Coral colunar', 'Porites astreoides', 'Cnidário', 'Poritidae', 'Carnívoro', 'Forma massas encrustantes ou nodulares com coloração amarelada marcante.'),
('Anêmona pescadora', 'Tealia felina', 'Cnidário', 'Urticinidae', 'Carnívoro', 'Revestida por cascalho e detritos aderidos ao seu corpo pegajoso para camuflagem.'),
('Água viva de fogo africana', 'Rhopilema nomadica', 'Cnidário', 'Rhizostomatidae', 'Carnívoro', 'Espécie invasora migratória no Mar Mediterrâneo com picadas dolorosas.'),
('Coral dedo', 'Porites porites', 'Cnidário', 'Poritidae', 'Carnívoro', 'Forma aglomerados de ramos curtos e grossos semelhantes a dedos grossos.'),
('Anêmona imperador', 'Condylactis aurantiaca', 'Cnidário', 'Actiniidae', 'Carnívoro', 'Possui tentáculos translúcidos com pontas coloridas contrastantes.'),
('Água viva cruciforme gigante', 'Stauromedusa geniculata', 'Cnidário', 'Staurozoa', 'Carnívoro', 'Forma séssil incomum que habita águas frias do norte.'),
('Coral formigueiro', 'Madracis mirabilis', 'Cnidário', 'Pocilloporidae', 'Carnívoro', 'Forma colônias densas de ramos finos e pontiagudos em águas mais profundas.'),
('Anêmona listrada', 'Diadumene lineata', 'Cnidário', 'Haliplanellidae', 'Carnívoro', 'Pequena anêmona invasora global com colônias marcadas por listras verticais verdes e brancas.'),
('Água viva lanterninha', 'Aequorea victoria', 'Cnidário', 'Aequoreidae', 'Carnívoro', 'Famosa na biologia molecular pela proteína verde fluorescente (GFP) extraída de seus tecidos.'),
('Coral tubo verde', 'Clavularia viridis', 'Cnidário', 'Clavulariidae', 'Carnívoro', 'Coral mole incrustante com pólipos que se assemelham a pequenas margaridas verdes brilhantes.'),
('Anêmona tapete', 'Stichodactyla haddoni', 'Cnidário', 'Stichodactylidae', 'Carnívoro', 'Habita fundos arenosos rasos, enterrando sua base e expandindo seu disco adesivo na superfície.'),
('Água viva cauda de cavalo', 'Dactylometra quinquecirrha', 'Cnidário', 'Pelagiidae', 'Carnívoro', 'Apresenta linhas marrons radiais na umbrella e tentáculos longos urticantes.'),
('Coral bola de neve', 'Scolymia cubensis', 'Cnidário', 'Mussidae', 'Carnívoro', 'Coral solitário com pólipo grande e carnoso exibindo cores fluorescentes sob luz azul.'),
('Anêmona pedunculada', 'Alicia mirabilis', 'Cnidário', 'Aliciidae', 'Carnívoro', 'Possui verrugas ramificadas cheias de nematocistos venenosos ao longo de sua coluna.'),
('Água viva comum do atlântico', 'Drymonema dalmatinum', 'Cnidário', 'Drymonematidae', 'Carnívoro', 'Predadora voraz de outras águas vivas, alcançando tamanhos impressionantes.'),
('Coral alface', 'Undaria tenuifolia', 'Cnidário', 'Agariciidae', 'Carnívoro', 'Suas colônias formam lâminas finas e onduladas que lembram folhas de alface dobradas.'),
('Anêmona de vidro', 'Exaiptasia diaphana', 'Cnidário', 'Aiptasiidae', 'Carnívoro', 'Possui corpo translúcido e delgado, amplamente estudada em pesquisas de simbiose.'),
('Água viva púrpura', 'Chrysaora hysosella', 'Cnidário', 'Pelagiidae', 'Carnívoro', 'Reconhecida pelas listras em forma de V marrons ou púrpuras em sua umbrella.'),
('Coral bambu', 'Isidis hippuris', 'Cnidário', 'Isididae', 'Carnívoro', 'Coral de profundidade com esqueleto segmentado em nós calcários e entrenós proteicos.'),

('Estrela do mar comum', 'Asterias rubens', 'Equinodermo', 'Asteriidae', 'Carnívoro', 'Predadora voraz de moluscos bivalves, abrindo suas conchas com os pés ambulacrários.'),
('Oriço do mar roxo', 'Strongylocentrotus purpuratus', 'Equinodermo', 'Echinidae', 'Herbívoro', 'Usa sua poderosa boca com mandíbulas (lanterna de aristóteles) para raspar algas das rochas.'),
('Pepino do mar comum', 'Holothuria tubulosa', 'Equinodermo', 'Holothuriidae', 'Detritívoro', 'Ingere sedimentos marinhos para filtrar matéria orgânica nutritiva no fundo do oceano.'),
('Estrela do mar coroa de espinhos', 'Acanthaster planci', 'Equinodermo', 'Acanthasteridae', 'Carnívoro', 'Especializada em se alimentar de pólipos de corais vivos, podendo causar desequilíbrios em recifes.'),
('Oriço do mar negro', 'Diadema antillarum', 'Equinodermo', 'Diadematidae', 'Herbívoro', 'Possui espinhos finos e longos extremamente venenosos que protegem recifes de supercrescimento de algas.'),
('Estrela do mar azul', 'Linckia laevigata', 'Equinodermo', 'Ophidiasteridae', 'Carnívoro', 'Apresenta coloração azul celeste marcante e regenera se facilmente de fragmentos corporais.'),
('Ofiúro frágil', 'Ophiothrix fragilis', 'Equinodermo', 'Ophiotrichidae', 'Detritívoro', 'Braços longos e flexíveis que se movem em serpenteando velozmente pelo substrato.'),
('Lírio do mar', 'Antedon bifida', 'Equinodermo', 'Antedonidae', 'Suspensívoro', 'Crinoide séssil ou de movimentos lentos que lembra uma flor delicada com braços plumosos.'),
('Bolacha da praia', 'Echinarachnius parma', 'Equinodermo', 'Scutellidae', 'Detritívoro', 'Equinodermo plano achatado em forma de moeda que vive enterrado em bancos de areia.'),
('Estrela girassol', 'Pycnopodia helianthoides', 'Equinodermo', 'Asteriidae', 'Carnívoro', 'Uma das maiores estrelas do mar do mundo, com dezenas de braços ágeis e vorazes.'),
('Pepino do mar leopardo', 'Bohadschia argus', 'Equinodermo', 'Holothuriidae', 'Detritívoro', 'Exibe manchas oculares características em seu corpo cilíndrico robusto.'),
('Oriço lápis', 'Heterocentrotus mammillatus', 'Equinodermo', 'Echinometridae', 'Herbívoro', 'Possui espinhos grossos e maciços em forma de lápis que resistem a fortes ondas.'),
('Estrela almofada', 'Oreaster reticulatus', 'Equinodermo', 'Oreasteridae', 'Carnívoro', 'Estrela robusta com corpo abaulado e textura reticulada rígida.'),
('Ofiúro gigante de cesto', 'Gorgonocephalus eucnemis', 'Equinodermo', 'Gorgonocephalidae', 'Suspensívoro', 'Seus braços ramificados complexos formam uma rede para capturar plâncton nas correntes profundas.'),
('Pepino do mar ananas', 'Thelenota ananas', 'Equinodermo', 'Stichopodidae', 'Detritívoro', 'Possui projeções cutâneas protuberantes que lembram a casca texturizada de um abacaxi.'),
('Oriço do mar verde', 'Strongylocentrotus droebachiensis', 'Equinodermo', 'Strongylocentrotidae', 'Herbívoro', 'Habita águas frias do norte, alimentando se avidamente de algas kelp.'),
('Estrela do mar de sangue', 'Henricia leviuscula', 'Equinodermo', 'Echinasteridae', 'Carnívoro', 'Coloração vermelha ou alaranjada viva, comum em poças de maré rochosas.'),
('Oriço tóxico', 'Toxopneustes pileolus', 'Equinodermo', 'Toxopneustidae', 'Herbívoro', 'Equipado com pedicelárias em forma de flor capazes de injetar toxinas dolorosas.'),
('Estrela batida', 'Patiria miniata', 'Equinodermo', 'Asterinidae', 'Carnívoro', 'Membranas interbraquiais estendidas dão um aspecto de estrela encorpada.'),
('Pepino do mar espinhoso', 'Apostichopus californicus', 'Equinodermo', 'Stichopodidae', 'Detritívoro', 'Importante espécie comercializada na Ásia pela sua textura e valor medicinal.'),
('Ofiúro verde', 'Ophiocoma scolopendrina', 'Equinodermo', 'Ophiocomidae', 'Detritívoro', 'Ativo durante a noite, estende seus braços de fendas rochosas para coletar detritos.'),
('Oriço do mar branco', 'Tripneustes gratilla', 'Equinodermo', 'Toxopneustidae', 'Herbívoro', 'Costuma camuflar se cobrindo o corpo com pedaços de algas e conchas.'),
('Estrela de areia', 'Archaster typicus', 'Equinodermo', 'Archasteridae', 'Detritívoro', 'Vive semi enterrada na areia rasa de praias tropicais protegidas.'),
('Pepino do mar preto', 'Holothuria atra', 'Equinodermo', 'Holothuriidae', 'Detritívoro', 'Revestido por uma camada de muco que frequentemente retém grãos de areia escura.'),
('Oriço do mar de rocha', 'Paracentrotus lividus', 'Equinodermo', 'Echinidae', 'Herbívoro', 'Capaz de escavar cavidades em rochas calcárias duras usando seus dentes e espinhos.'),
('Estrela cometa', 'Linckia guildingi', 'Equinodermo', 'Ophidiasteridae', 'Carnívoro', 'Conhecida por se reproduzir assexuadamente por fissão e regeneração de braços isolados.'),
('Ofiúro reticulado', 'Ophionereis reticulata', 'Equinodermo', 'Ophionereididae', 'Detritívoro', 'Possui um padrão de rede geométrica delicada na superfície dorsal do disco central.'),
('Lírio do mar plumoso', 'Comaster schlegelii', 'Equinodermo', 'Comasteridae', 'Suspensívoro', 'Possui dezenas de braços plumosos coloridos que capturam plâncton na correnteza.'),
('Bolacha da praia gigante', 'Dendraster excentricus', 'Equinodermo', 'Dendrasteridae', 'Detritívoro', 'Forma densos leitos verticais em fundos arenosos expostos às ondas.'),
('Estrela fragilizada vermelha', 'Ophioderma brevispinum', 'Equinodermo', 'Ophiodermatidae', 'Detritívoro', 'Disco central robusto com braços curtos e grossos que se movem de forma serpentina.'),
('Pepino do mar amarelo', 'Cucumaria frondosa', 'Equinodermo', 'Cucumariidae', 'Suspensívoro', 'Estende tentáculos orais ramificados em forma de árvore para filtrar alimento da água.'),
('Oriço do mar coração', 'Echinocardium cordatum', 'Equinodermo', 'Loveniidae', 'Detritívoro', 'Possui simetria bilateral secundária e vive profundamente enterrado no sedimento arenoso.'),
('Estrela das profundidades', 'Bathybiaster vexillifer', 'Equinodermo', 'Benthopectinidae', 'Carnívoro', 'Habita regiões abissais frias alimentando se de detritos e pequenos invertebrados.'),
('Pepino do mar vermelho', 'Parastichopus parvimensis', 'Equinodermo', 'Stichopodidae', 'Detritívoro', 'Exibe coloração avermelhada com tubérculos proeminentes e alimenta se de matéria orgânica.'),
('Ofiúro de espinhos longos', 'Ophiothrix spiculata', 'Equinodermo', 'Ophiotrichidae', 'Detritívoro', 'Possui espinhos transparentes e espinhosos ao longo de seus longos braços.'),
('Oriço diadema austral', 'Centrostephanus coronatus', 'Equinodermo', 'Diadematidae', 'Herbívoro', 'Encontrado em recifes rochosos, possui espinhos longos e escuros com anéis.'),
('Estrela de porcelana', 'Fromia monilis', 'Equinodermo', 'Ophidiasteridae', 'Carnívoro', 'Apresenta placas coloridas contrastantes que lembram peças de mosaico de porcelana.'),
('Pepino do mar gigante cinza', 'Stichopus chloronotus', 'Equinodermo', 'Stichopodidae', 'Detritívoro', 'Corpo verde escuro alongado com papilas dorsais pontiagudas.'),
('Lírio do mar de coral', 'Cenometra bella', 'Equinodermo', 'Colobometridae', 'Suspensívoro', 'Vive empoleirado em gorgônias e corais em busca de correntes ricas em plâncton.'),
('Oriço do mar de fogo', 'Asthenosoma varium', 'Equinodermo', 'Echinothuriidae', 'Herbívoro', 'Possui testas flexíveis e espinhos ocos venenosos muito perigosos.'),
('Estrela do mar de rasteiro', 'Leptasterias polaris', 'Equinodermo', 'Asteriidae', 'Carnívoro', 'Estrela friorentas que incuba seus ovos diretamente sob o corpo em vez de liberá los na água.'),
('Pepino do mar dragão', 'Synapta maculata', 'Equinodermo', 'Synaptidae', 'Detritívoro', 'Pepino serpenteiforme extremamente longo que carece de pés ambulacrários locomotores tradicionais.'),
('Oriço do mar verde escuro', 'Echinometra lucunter', 'Equinodermo', 'Echinometridae', 'Herbívoro', 'Comum na zona intertidal rochosa brasileira, adaptado a fortes impactos de ondas.'),
('Estrela alvinegra', 'Nardoa tuberculata', 'Equinodermo', 'Ophidiasteridae', 'Carnívoro', 'Apresenta tubérculos arredondados distribuídos ao longo de seus braços roliços.'),
('Ofiúro malhado', 'Ophiolepis paucispina', 'Equinodermo', 'Ophiolepididae', 'Detritívoro', 'Pequeno ofiúro que habita fendas em recifes de coral rasos.'),
('Pepino do mar marrom', 'Holothuria forskali', 'Equinodermo', 'Holothuriidae', 'Detritívoro', 'Capaz de ejetar fios pegajosos de Cuvier quando severamente ameaçado por predadores.'),
('Oriço do mar do mediterrâneo', 'Sphaerechinus granularis', 'Equinodermo', 'Toxopneustidae', 'Herbívoro', 'Possui espinhos curtos e grossos com pontas arroxeadas ou brancas.'),
('Estrela do mar espinhosa do atlântico', 'Marthasterias glacialis', 'Equinodermo', 'Asteriidae', 'Carnívoro', 'Grandes espinhos cônicos dispostos em três fileiras ao longo de cada braço.'),
('Lírio do mar elegante', 'Tropometra carinata', 'Equinodermo', 'Tropometridae', 'Suspensívoro', 'Espécie tropical que se agarra a corais e rochas em águas de forte correnteza.'),
('Pepino do mar marinho amarelo escuro', 'Colochirus robustus', 'Equinodermo', 'Cucumariidae', 'Suspensívoro', 'Exibe coloração amarela ou laranja viva com tentáculos ramificados vistosos.'),
('Oriço do mar violeta', 'Arbacia lixula', 'Equinodermo', 'Arbaciidae', 'Herbívoro', 'Reconhecido por sua coloração preta ou roxa escura profunda e carapaça nua no ápice.'),
('Estrela de pintas laranja', 'Fromia indica', 'Equinodermo', 'Ophidiasteridae', 'Carnívoro', 'Pequena estrela com corpo avermelhado e manchas laranja contrastantes.'),
('Pepino do mar espinhento marrom', 'Actinopyga mauritiana', 'Equinodermo', 'Holothuriidae', 'Detritívoro', 'Habita recifes rasos de águas turbulentas, alimentando se de areia rica emnutrientes.'),
('Ofiúro de braços listrados', 'Ophiocoma wendtii', 'Equinodermo', 'Ophiocomidae', 'Detritívoro', 'Possui células em sua pele que funcionam como lentes ópticas naturais, agindo como um olho composto'),
('Oriço do mar australiano', 'Heliocidaris erythrogramma', 'Equinodermo', 'Echinometridae', 'Herbívoro', 'Endêmico da Austrália, com espinhos curtos de tons avermelhados ou esverdeados.'),
('Estrela do mar roxa do pacífico', 'Pisaster ochraceus', 'Equinodermo', 'Asteriidae', 'Carnívoro', 'Espécie chave em ecossistemas de poças de maré na costa oeste norte americana.'),
('Pepino do mar roxo escuro', 'Pseudocolochirus violaceus', 'Equinodermo', 'Cucumariidae', 'Suspensívoro', 'Apresenta tentáculos orais ramificados de cor violeta brilhante para captação de plâncton'),
('Oriço do mar perfurador', 'Echinometra mathaei', 'Equinodermo', 'Echinometridae', 'Herbívoro', 'Amplamente distribuído no Indo Pacífico, abriga se em rochas calcárias erodidas.'),
('Estrela do mar de areia fina', 'Astropecten aranciacus', 'Equinodermo', 'Astropectinidae', 'Carnívoro', 'Estrela de areia com margens pectinadas, caçadora noturna de moluscos e vermes.'),
('Ofiúro de braços longos', 'Amphipholis squamata', 'Equinodermo', 'Amphiuridae', 'Detritívoro', 'Pequeno ofiúro cosmopolita que incuba seus ovos internamente até a eclosão.'),
('Lírio do mar gigante de fenda', 'Lamprometra palmata', 'Equinodermo', 'Mariametridae', 'Suspensívoro', 'Crinoide tropical com múltiplos braços flexíveis que formam leques filtradores.');
   
    UPDATE insetos SET foto_insetos CASE id_insetos
    WHEN 1 THEN foto_insetos = 'https://cults3d.com/pt/modelo-3d/arte/rhinoceros-beetle-aletrzoda?srsltid=AU7gw4XiIV_0iDbssxYQ5CR2d5SKN9V0Y8Io868xHtI5FRM6i7Y4Z81W',
    WHEN 2 THEN foto_insetos = 'https://g1.globo.com/sp/campinas-regiao/terra-da-gente/noticia/2023/09/18/pequeno-gigante-conheca-besouro-que-mede-17-cm-e-consegue-levantar-ate-850-vezes-seu-peso.ghtml',
    WHEN 3 THEN foto_insetos = 'https://darwinianas.com/2017/07/11/o-que-voce-sabe-sobre-os-besouros-rola-bostas/',
    WHEN 4 THEN foto_insetos = 'https://pictureinsect.com/pt/wiki/Goliathus_goliatus.html',
    WHEN 5 THEN foto_insetos = 'https://pt.wikipedia.org/wiki/Ficheiro:Elephant_Beetle_Megasoma_elephas_Male_Top_2170px.jpg',
    WHEN 6 THEN foto_insetos = 'https://www.reddit.com/r/macrophotography/comments/1jlkzgb/brown_marmorated_stink_bug/?tl=pt-br',
    WHEN 7 THEN foto_insetos = 'https://pictureinsect.com/pt/wiki/Chrysolina_herbacea.html',
    WHEN 8 THEN foto_insetos = 'https://pictureinsect.com/pt/wiki/Chalcosoma_atlas.html',
    WHEN 9 THEN foto_insetos = 'https://www.facebook.com/biologismo/posts/este-besouro-maravilhoso-%C3%A9-o-besouro-j%C3%B3ia-dourado-anoplognathus-aureus-uma-esp%C3%A9c/753635645321407/',
    WHEN 10 THEN foto_insetos = 'https://www.cnpuv.embrapa.br/uzum/uva/besouro.html',
    WHEN 11 THEN foto_insetos = 'https://www.mundoecologia.com.br/animais/besouro-violino-caracteristicas-nome-cientifico-e-fotos/',
    WHEN 12 THEN foto_insetos = 'https://super.abril.com.br/ciencia/besouro-usa-pum-mortal-para-se-defender-de-predadores/',
    WHEN 13 THEN foto_insetos = 'https://umsoplaneta.globo.com/biodiversidade/noticia/2025/07/04/fantastico-mudo-animal-este-besouro-que-troca-o-dourado-pelo-rubi-em-segundos.ghtml',
    WHEN 14 THEN foto_insetos = 'https://pt.vecteezy.com/foto/3780711-besouro-tigre-verde',
    WHEN 15 THEN foto_insetos = 'https://www.istockphoto.com/br/fotos/carabus-violaceus',
    WHEN 16 THEN foto_insetos = 'http://www.portal.zoo.bio.br/media2135',
    WHEN 17 THEN foto_insetos = 'https://saocarlosemrede.com.br/besouro-tigre-velocidade-precisao-caca-g4/',
    WHEN 18 THEN foto_insetos = 'url',
    WHEN 19 THEN foto_insetos = 'url',
    WHEN 20 THEN foto_insetos = 'url',
    WHEN 21 THEN foto_insetos = 'url',
    WHEN 22 THEN foto_insetos = 'url',
    WHEN 23 THEN foto_insetos = 'url',
    WHEN 24 THEN foto_insetos = 'url',
    WHEN 25 THEN foto_insetos = 'url',
    WHEN 26 THEN foto_insetos = 'url',
    WHEN 27 THEN foto_insetos = 'url',
    WHEN 28 THEN foto_insetos = 'url',
    WHEN 29 THEN foto_insetos = 'url',
    WHEN 30 THEN foto_insetos = 'url',
    WHEN 31 THEN foto_insetos = 'url',
    WHEN 32 THEN foto_insetos = 'url',
    WHEN 33 THEN foto_insetos = 'url',
    WHEN 34 THEN foto_insetos = 'url',
    WHEN 35 THEN foto_insetos = 'url',
    WHEN 36 THEN foto_insetos = 'url',
    WHEN 37 THEN foto_insetos = 'url',
    WHEN 38 THEN foto_insetos = 'url',
    WHEN 39 THEN foto_insetos = 'url',
    WHEN 40 THEN foto_insetos = 'url',
    WHEN 41 THEN foto_insetos = 'url',
    WHEN 42 THEN foto_insetos = 'url',
    WHEN 43 THEN foto_insetos = 'url',
    WHEN 44 THEN foto_insetos = 'url',
    WHEN 45 THEN foto_insetos = 'url',
    WHEN 46 THEN foto_insetos = 'url',
    WHEN 47 THEN foto_insetos = 'url',
    WHEN 48 THEN foto_insetos = 'url',
    WHEN 49 THEN foto_insetos = 'url',
    WHEN 50 THEN foto_insetos = 'url',
    -- 11 á 366 depois
    ELSE foto_insetos
    END
    WHERE id_insetos BETWEEN 1 AND 366; -- adicione 11 á 366 
    


    UPDATE insetos SET destaque = 1 WHERE id_insetos IN(1, 62, 123, 184, 245, 306);
        SELECT * FROM insetos;

CREATE TABLE habitats (
    id_habitats INT AUTO_INCREMENT PRIMARY KEY,
    nome_habitats VARCHAR(50),
    clima_habitats VARCHAR(50),
    bioma_habitats VARCHAR(65),
    descricao_habitats TEXT, 
     id_insetos INT, 
    CONSTRAINT fk_habitats_insetos  FOREIGN KEY (id_insetos) 
    REFERENCES insetos(id_insetos)
);

INSERT INTO (nome_habitats)
TRUNCATE Table insetos;
SELECT * FROM insetos;
